# Generated by Django 4.1.6 on 2023-02-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quest', models.CharField(choices=[('K', 'Kill'), ('F', 'Fetch'), ('E', 'Escort'), ('G', 'Gather'), ('D', 'Delivery'), ('M', 'Mystery'), ('L', 'Lore')], default='K', max_length=1)),
                ('details', models.TextField(max_length=250)),
                ('trinket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trinket')),
            ],
        ),
    ]
