# Generated by Django 4.1.6 on 2023-02-09 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uses',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='uses',
            name='date',
            field=models.DateField(verbose_name='date of usage'),
        ),
        migrations.AlterField(
            model_name='uses',
            name='quest',
            field=models.CharField(choices=[('F', 'Fetch'), ('E', 'Escort'), ('G', 'Gather'), ('K', 'Kill'), ('D', 'Delivery'), ('M', 'Mystery'), ('L', 'Lore')], default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='TrinketInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.merchant')),
                ('trinket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trinket')),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='trinkets',
            field=models.ManyToManyField(through='main_app.TrinketInventory', to='main_app.trinket'),
        ),
    ]
