# Generated by Django 4.1.6 on 2023-02-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merchant_alter_uses_options_alter_uses_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='trinkets',
        ),
        migrations.AddField(
            model_name='trinket',
            name='merchants',
            field=models.ManyToManyField(to='main_app.merchant'),
        ),
        migrations.DeleteModel(
            name='TrinketInventory',
        ),
    ]
